### ISSUE TITLE
q39 - Create the website index page and publish it

### ISSUE THREAD

**Issue by Mantaseus** [Navleenkaursandhu/notebook#42]
# Task 1 - Create `index.html` file
- Create a new webpage called `index.html` at the base of the repository. It should look like this

  ![image](https://user-images.githubusercontent.com/36828664/172886269-0bf728c7-226e-424c-89e2-eb9cb60a7f28.png)

- You can use the following HTML template as a starting point
  
  ```html
  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>My projects</title>
  
      <style>
        body {
          padding: 0;
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }
      </style>
    </head>
  
    <body>
      <!-- Your stuff goes here -->
    </body>
  </html>
  
  ```
- Notes
  - The green boxes for each question in the reference image are `<a/>` elements whose `href` is a relative link to the HTML file you created for the given question
  - Make sure that the links open in a new tab
  - The styling for the green boxes is similar to the button you created in `q11`, The only differences are
    - There is a border radius on the box
    - Try to use `margin-top` in the `:hover` and `:active` definitions on the buttons instead of `border-top` because it will look even if the background color of the container is not white. It also does not affect the roundness of the top rounded corners
    - Try to use a transparent color (like `#0006`) for the bottom border. This way, the "shadow" at the bottom of the button will actually take on whatever background color you set for the button itself. It is just more maintainable
  - The `max-width` of the content on the page is `800px`
  - The rest is up to you. You can style it however you like

# Task 2 - Publish to github pages

- Learn about [github pages](https://docs.github.com/en/pages/quickstart). It is a free way to host your website using github
  - You can also look at the tutorial [here](https://www.theodinproject.com/lessons/foundations-recipes#viewing-your-project-on-the-web). I think the steps here will be easier to follow for our case.
- Deploy your development branch using github pages and make sure all the links actually work
  - Note: Deploy your development branch. Don't worry about `main`
- Create a PR and get the changes merged
- Finally, deploy the `main` branch

**Comment by Mantaseus** [comment]
An improvement to the design of the links would be to make their shape actually look rounded

![image](https://user-images.githubusercontent.com/36828664/173188748-fac57594-f2f7-498c-be61-d6cc18827a73.png)

The issue is that by using the borders for the 3D effect, the border radius does not apply consistently at each normal, `:hover` and `:active` state.

Hint: one solution you can use will involve negative bottom margins and creating a solid shadow going down (using `box-shadow`) that will take the place of the bottom border

**Comment by Navleenkaursandhu** [comment]
tried altering the styling of button, please review
